# Generated by Django 4.2.6 on 2023-11-19 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('comment', 'comment on a post'), ('follow', 'new follow')], verbose_name='Activity Type')),
                ('object_type', models.CharField(choices=[('comment', 'Comment'), ('follow', 'Follow')], verbose_name='Object type')),
                ('object_url', models.URLField(verbose_name='Object URL')),
                ('time_sent', models.DateTimeField(auto_now_add=True, verbose_name='Time sent')),
                ('is_unread', models.BooleanField(default=True, verbose_name='Is unread')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
