# Generated by Django 4.2.7 on 2024-01-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient'], name='notification_recipient_idx'),
        ),
    ]
