# Generated by Django 4.2.6 on 2023-10-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_litteruser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litteruser',
            name='bio',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Bio'),
        ),
    ]
