# Generated by Django 4.2.6 on 2023-10-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_language_remove_post_language_post_languages'),
        ('users', '0003_alter_litteruser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='litteruser',
            name='languages',
            field=models.ManyToManyField(to='core.language'),
        ),
    ]
