# Generated by Django 4.2.6 on 2023-11-01 16:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_litteruser_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='litteruser',
            name='picture',
            field=models.ImageField(default='default_pp.png', upload_to=core.models.PathAndRename('profile_pics/')),
        ),
    ]
