# Generated by Django 4.2.7 on 2024-01-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_litteruser_litteruser_id_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='litteruser',
            name='litteruser_id_idx',
        ),
    ]
