# Generated by Django 4.2.7 on 2024-01-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_comment_total_votes_post_total_votes_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user'], name='comment_user_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post'], name='comment_post_idx'),
        ),
        migrations.AddIndex(
            model_name='commentvote',
            index=models.Index(fields=['user', 'comment'], name='commentvote_user_comment_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user'], name='post_user_idx'),
        ),
        migrations.AddIndex(
            model_name='postvote',
            index=models.Index(fields=['user', 'post'], name='postvote_user_post_idx'),
        ),
    ]
