# Generated by Django 4.2.7 on 2024-01-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_comment_comment_user_idx_comment_comment_post_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['id'], name='post_id_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created'], name='post_desc_created_idx'),
        ),
        migrations.AddIndex(
            model_name='postvote',
            index=models.Index(fields=['post'], name='postvote_post_idx'),
        ),
        migrations.AddIndex(
            model_name='postvote',
            index=models.Index(fields=['user'], name='postvote_user_idx'),
        ),
    ]
