# Generated by Django 4.2.7 on 2024-01-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_post_post_created_idx'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='commentvote',
            name='Unique comment vote.',
        ),
        migrations.RemoveConstraint(
            model_name='postvote',
            name='Unique post vote.',
        ),
        migrations.RemoveIndex(
            model_name='commentvote',
            name='commentvote_user_comment_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='post_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='post_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='postvote',
            name='postvote_user_post_idx',
        ),
        migrations.RemoveIndex(
            model_name='postvote',
            name='postvote_post_idx',
        ),
        migrations.RemoveIndex(
            model_name='postvote',
            name='postvote_user_idx',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created'], name='comment_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-total_votes'], name='post_total_votes_idx'),
        ),
        migrations.AddConstraint(
            model_name='commentvote',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='commentvote_user_comment_idx'),
        ),
        migrations.AddConstraint(
            model_name='postvote',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='postvote_user_post_idx'),
        ),
    ]
